### ISSUE TITLE
Compliance Horizon Scanning Ready for TSC Review

### ISSUE THREAD

**Issue by mcleo-d** [finos/technical-steering-committee#39]
Hi @ColinEberhardt and the TSC,

@sndpkumar14 and the Synechron team is ready to present the proposed **Compliance Horizon Scanning** contribution (https://github.com/finos/community/issues/195) to the FINOS TSC.

Can you provide guidance and a date for when the presentation to the TSC can take place?

Kind regards,

James.

**Comment by ColinEberhardt** [comment]
HI @mcleo-d thanks for the heads-up, I'll start organising a suitable time. We have Vuu in the queue already.

Can you please apply the [ready for tsc](https://github.com/finos/community/issues?q=is%3Aissue+is%3Aopen+label%3Aready-for-tsc) label? I'll make sure it moves to the right lane in our project board

**Comment by mcleo-d** [comment]
Done - Thanks @ColinEberhardt

**Comment by ColinEberhardt** [comment]
covered by https://github.com/finos/community/issues/195
