### ISSUE TITLE
Need meeting soon on TSC charter to stay on track

### ISSUE THREAD

**Issue by caradelia** [finos/technical-steering-committee#55]
@ColinEberhardt We mentioned  a working session for the TSC strategy prior to our next monthly meeting. Happy to help get that on calendars so that we can stay on track to get this framework to the Board.

**Comment by ColinEberhardt** [comment]
Thanks for raising this @caradelia - I've been on holiday and it hasn't quite made it to the top of my priority list yet. My current plan for this week is to:

- draft the TSC charter, this will be a combination of
   - [TSC responsibilities](https://github.com/finos/technical-steering-committee/blob/master/meetings/2023-01-18.md#tsc-responsibilities) we discussed in a previous meeting, that were well received by the board.
   - the TSC formation and composition [as discussed previously](https://github.com/finos/technical-steering-committee/discussions/52)
- share this draft with FINOS (I have a catch-up with Gab on Thursday)
- following this, share with the TSC

With this in mind, it might be better to aim for our next scheduled TSC meeting.

If you'd like to help, I'd be happy to share a draft with you tomorrow?

**Comment by caradelia** [comment]
Yes, if you could share out that would be great. Probably best to share out
to all theTSC to be fully transparent and preemptively receive input.

**Comment by jonfreedman** [comment]
@caradelia I think we can close this now?
