### ISSUE TITLE
2023 Jun 20 - Technical Steering Committee Meeting Minutes

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/technical-steering-committee#69]
## Date
2023/06/20 

### Zoom Info
(Tuesday Meeting)
- Meeting link: https://zoom.us/j/92917330824
- Meeting number: 929 1733 0824
- Password: Check the email invite

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] project contribution proposal https://github.com/finos/community/issues/273
- [ ] Continued discussion on the FINOS project lifecycle

**Comment by ColinEberhardt** [comment]
Hi Juan, thanks for the heads up. The TSC handles project contributions asynchronously, as describe here:

https://github.com/finos/technical-steering-committee/blob/master/responsibilities.md#project-contributions

If it’s ready for review, I can find a TSC volunteer?

**Comment by TheJuanAndOnly99** [comment]
@ColinEberhardt Just wanted to quickly mention it. We are in the process of socializing the contribution to see if there is any interest from the community. I think in ~2 weeks it should be ready for the official review. We'll let you know when.
